# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

DEVELOPER_KEY_ID = ENV['DEVELOPER_KEY_ID']
DEVELOPER_KEY_ISSUER_ID = ENV['DEVELOPER_KEY_ISSUER_ID']
DEVELOPER_KEY_CONTENT = ENV['DEVELOPER_KEY_CONTENT']

add_extra_platforms(platforms: [:tvos])

before_all do
  update_fastlane
end

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    app_store_connect_api_key(
      key_id: DEVELOPER_KEY_ID,
      issuer_id: DEVELOPER_KEY_ISSUER_ID,
      key_content: DEVELOPER_KEY_CONTENT
    )

    build = get_build_number(xcodeproj: "Yattee.xcodeproj")
    version = get_version_number(
      xcodeproj: "Yattee.xcodeproj",
      target: "Yattee (iOS)"
    )

    build_app(
      scheme: "Yattee (iOS)",
      output_directory: "fastlane/builds/#{version}-#{build}/iOS",
      output_name: "Yattee-#{version}-iOS.ipa",
      xcargs: "-allowProvisioningUpdates"
    )

    altool(
      altool_app_type: "ios",
      altool_ipa_path: lane_context[SharedValues::IPA_OUTPUT_PATH]
    )
  end
end

platform :tvos do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    app_store_connect_api_key(
      key_id: DEVELOPER_KEY_ID,
      issuer_id: DEVELOPER_KEY_ISSUER_ID,
      key_content: DEVELOPER_KEY_CONTENT
    )

    build = get_build_number(xcodeproj: "Yattee.xcodeproj")
    version = get_version_number(
      xcodeproj: "Yattee.xcodeproj",
      target: "Yattee (tvOS)"
    )

    build_app(
      scheme: "Yattee (tvOS)",
      output_directory: "fastlane/builds/#{version}-#{build}/tvOS",
      output_name: "Yattee-#{version}-tvOS.ipa",
      xcargs: "-allowProvisioningUpdates"
    )

    altool(
      altool_app_type: "tvos",
      altool_ipa_path: lane_context[SharedValues::IPA_OUTPUT_PATH]
    )
  end
end

platform :mac do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    app_store_connect_api_key(
      key_id: DEVELOPER_KEY_ID,
      issuer_id: DEVELOPER_KEY_ISSUER_ID,
      key_content: DEVELOPER_KEY_CONTENT
    )

    build = get_build_number(xcodeproj: "Yattee.xcodeproj")
    version = get_version_number(
      xcodeproj: "Yattee.xcodeproj",
      target: "Yattee (macOS)"
    )

    build_app(
      scheme: "Yattee (macOS)",
      output_directory: "fastlane/builds/#{version}-#{build}/macOS",
      output_name: "Yattee-#{version}-macOS.app",
      xcargs: "-allowProvisioningUpdates"
    )

    altool(
      altool_app_type: "macos",
      altool_ipa_path: lane_context[SharedValues::PKG_OUTPUT_PATH]
    )
  end
end
